### ISSUE TITLE
What about the starter card?

### ISSUE THREAD

**Issue by dario-campagna** [nicdom23/Cribbage-assignment#1]
Is a test for parsing the complete hand missing?

https://github.com/nicdom23/Cribbage-assignment/blob/c13ae657ff8c1ebe434a865296d68907a1d4d349/src/test/java/dssc/assignment/cribbage/ParseHandTest.java#L29

**Comment by nicdom23** [comment]
Misnomed test. Corrected it to parseFiveCards
