### ISSUE TITLE
Methods readability

### ISSUE THREAD

**Issue by dario-campagna** [nicdom23/Cribbage-assignment#10]
The methods in this class are not easy to read and understand. Some method names could be more intention revealing. Some methods are a bit too long (due to nested for-loops and if-statement).

https://github.com/nicdom23/Cribbage-assignment/blob/c13ae657ff8c1ebe434a865296d68907a1d4d349/src/main/java/dssc/assignment/cribbage/PointCalculator.java#L3

**Comment by nicdom23** [comment]
I tried a small renaming of all methods, but maybe it's not enough...
