### ISSUE TITLE
Test names should communicate as much as possible

### ISSUE THREAD

**Issue by dario-campagna** [nicdom23/Cribbage-assignment#2]
Test names like this (and `fifteen_two_Points3`, `parseOneCard1`) are not that helpful. When a test fails, the first thing you see is its name. The more information we get from the name, the better. 

https://github.com/nicdom23/Cribbage-assignment/blob/c13ae657ff8c1ebe434a865296d68907a1d4d349/src/test/java/dssc/assignment/cribbage/CountHandPointsTest.java#L12

**Comment by nicdom23** [comment]
Renamed tests, I hope they are more clear now
