### ISSUE TITLE
equals for Hand and Card

### ISSUE THREAD

**Issue by dario-campagna** [nicdom23/Cribbage-assignment#4]
If you implement the `equals` (and `hashCode`) method for `Hand` and `Card` classes you can simplify the assertion in this test and in the other two tests.

https://github.com/nicdom23/Cribbage-assignment/blob/c13ae657ff8c1ebe434a865296d68907a1d4d349/src/test/java/dssc/assignment/cribbage/ParseHandTest.java#L31

**Comment by nicdom23** [comment]
Thanks, I learned a lot by solving this Issue.
