### ISSUE TITLE
Primitive obsession

### ISSUE THREAD

**Issue by dario-campagna** [nicdom23/Cribbage-assignment#5]
The card Rank is more than just a character. In the `getRankInt` method you have the numerical aspect of the rank. In `PointCalculator` you have the rank order encoded in a String.

https://github.com/nicdom23/Cribbage-assignment/blob/c13ae657ff8c1ebe434a865296d68907a1d4d349/src/main/java/dssc/assignment/cribbage/Card.java#L4

**Comment by nicdom23** [comment]
Maybe I can fix this if I add a static variable "A1234567890JQK" and also a private int rankAsInt?

**Comment by nicdom23** [comment]
That would collect all the primitive obsession into one class maybe making it less smelly, I guess?

**Comment by nicdom23** [comment]
Of course I would need to change CardParser and the Card class builder.

**Comment by dario-campagna** [comment]
It could be a step in the right direction. From there you could then move the rank-related fields into a new class.

**Comment by nicdom23** [comment]
I tried to enrich the Card class with the extra element rankAsInt, so I skip the if cycle when I have to get rank as an integer. 
A rank class you say? Is it better? I will try now.

**Comment by nicdom23** [comment]
Ok, I created a class Rank, does this close the issue, maybe?

**Comment by dario-campagna** [comment]
Yes, we can say that with the Rank class we removed the primitive obsession smell. At the same, the Rank class has the same smell of Card and Hand, data class. That’s fine, as we refactor we shape our code and learn more about how we can shape it. A question that now could help in further refactoring is: “what operations could we move in these data classes?”.
