### ISSUE TITLE
Unnecessarily complex condition

### ISSUE THREAD

**Issue by dario-campagna** [nicdom23/Cribbage-assignment#6]
The call to Character.compare is redundant and you could use the `asChar` method of `Suite` (that is unused). The `if` condition can be rewritten as `refSuite.asChar() == cardAsText.charAt(1)`. 

https://github.com/nicdom23/Cribbage-assignment/blob/c13ae657ff8c1ebe434a865296d68907a1d4d349/src/main/java/dssc/assignment/cribbage/CardParser.java#L6

**Comment by nicdom23** [comment]
Thank you for the tip. I corrected it and the tests passed.
