### ISSUE TITLE
Large class (code smell)

### ISSUE THREAD

**Issue by dario-campagna** [nicdom23/Cribbage-assignment#7]
This class has too many lines of code. One of the reason this class is large is that it mixes two things, computing the points and looking for card combinations. For example, in this class we have both the logic to compute the points for a given number of fifteen-twos, and the logic to determine the how many fifteen-twos there are in a hand.

https://github.com/nicdom23/Cribbage-assignment/blob/c13ae657ff8c1ebe434a865296d68907a1d4d349/src/main/java/dssc/assignment/cribbage/PointCalculator.java#L3

**Comment by nicdom23** [comment]
I tried refactoring via adding a new class for each point type to collect most of the calculations of the points.

**Comment by dario-campagna** [comment]
Now another code smell is more evident, feature envy. The new classes have no fields. The methods in this classes use only the arguments. One argument that appears in almost every method is Hand. These methods mix computing the score and retrieving the number of certain card combinations. Can we separate these two responsibilities?

**Comment by nicdom23** [comment]
To compute the score we need to know the rank or the suite of all cards. The score is computed after all possible combinations are inspected. What do you mean by "retrieving the number of certain card combination"? What number? Rank or Suite? And What for? Don't we do it to parse the combinations to compute the score?

**Comment by nicdom23** [comment]
Because now the methods dealCardsRankInt, dealCardsSuite and dealCardsRank seem to do that, I fail to see how more separate they should be. Maybe are you trying to say that I need to think again my implementation?

**Comment by dario-campagna** [comment]
Take for example the score for pairs. To compute it you can multiply the number of distinct pairs by 2. The number of distinct pairs is an example of what I mean with “number of certain cards combination”. Counting the numbers of distinct pairs could be a responsibility of Hand.

**Comment by dario-campagna** [comment]
In the current code you need to access through Hand the cards rank and suit. Moving the code that manipulates those data close to the data itself could remove more than one smell.
