### ISSUE TITLE
Message chains

### ISSUE THREAD

**Issue by dario-campagna** [nicdom23/Cribbage-assignment#8]
Here and in other methods in this class we ask a card to the hand to then get the card rank or suit. These data are then used to search for card combinations in the hand. This smell can give us some idea about how to reduce the lines of code in this class.

https://github.com/nicdom23/Cribbage-assignment/blob/c13ae657ff8c1ebe434a865296d68907a1d4d349/src/main/java/dssc/assignment/cribbage/PointCalculator.java#L24

**Comment by nicdom23** [comment]
As I said in the Data Class Issue, maybe by putting the Card class inside the Hand class a solution can be found for this issue too...

**Comment by dario-campagna** [comment]
It could be. I think that the message chain smell is just a consequence of the data class smell.

**Comment by nicdom23** [comment]
I'm not really sure. I avoided mixing the Card Class with the Hand class as it would have elongated message chains. Instead I wrote more methods(dealCardRankInt(),dealCardRank(), and dealCardSuite()) so now there is a unique call to the wanted method. Now hand is longer, but I removed a longer call. Close the issue if you think it is ok, please.
I am getting suspicious. My efforts to trying to remove smells seem to introduce different smells instead...
I tried to remove message chains but instead I introduced repetition and a longer class Hand. I abused of for loops. I got an idea to reduce repetition.

**Comment by nicdom23** [comment]
Nice, I implemented it. Now I have reduced both repetition and long class smell for the class Hand. You might think that this way is better than before.
