### ISSUE TITLE
Data Class (code smell)

### ISSUE THREAD

**Issue by dario-campagna** [nicdom23/Cribbage-assignment#9]
This class is a good example of the Data Class code smell. It contains only fields and methods for accessing them.

https://github.com/nicdom23/Cribbage-assignment/blob/c13ae657ff8c1ebe434a865296d68907a1d4d349/src/main/java/dssc/assignment/cribbage/Hand.java#L3

**Comment by nicdom23** [comment]
Now that I overrode equals and hashCode is it still a code smell?

**Comment by nicdom23** [comment]
I set the elements of the class as privates.  Is it a good idea to put the class Card inside the class Hand? That would seem reasonable to me...

**Comment by nicdom23** [comment]
Perhaps it would solve the Message chain code smell too?

**Comment by nicdom23** [comment]
I also thought last night about compacting Card and CardParser into one class, and also Hand and HandParser into one class. That would solve the Data Class smell and also maybe again the message chain class smell.

**Comment by nicdom23** [comment]
Ok, I combined Hand and HandParser and Card and CardParser. I still need to solve the message chain Issue, this maybe by combining the class Card into the class Hand...

**Comment by nicdom23** [comment]
Is the code smell Data Class removed now? Or is it worse?

**Comment by dario-campagna** [comment]
An instance of the Hand class still doesn't operate independently on the data it owns (i.e. the cards). The previous version, with the HandParser and CardParser was better from the point of view of the single responsibility principle.

**Comment by nicdom23** [comment]
But aren't HandParser and CardParser examples of feature envy? As I said in another comment, maybe by removing smells I tend to introduce others as you are giving me this example.

**Comment by dario-campagna** [comment]
HandParser and CardParser only had the static method that turns a string into some other object. That’s not feature envy. Having them in separate classes helps spreading the different responsibilities you have in the code in my opinion.

**Comment by nicdom23** [comment]
So I have re-added the two classes, and I think this issue is therefore closed. Thank you for your help.
